name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci

  unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - run: npm test:ci:unit

  e2e:
    name: Run e2e tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - run: npm test:ci:e2e
